### ISSUE TITLE
error Command failed with exit code 1: npm install

### ISSUE THREAD

**Issue by narr07** [kosvrouvas/gatsby-tailwindcss-starter#117]
How to fix it?

npm ERR! This is an error with npm itself. Please report this error at:
  Error: Command failed with exit code 1: npm install

  - error.js:56 makeErrorf this run can be found in:
    [npm]/[gatsby-cli]/[execa]/lib/error.js:56:11ng\npm\_logs\2020-12-05T03_59_07_302Z-debug.log

  - index.js:114 handlePromise
    [npm]/[gatsby-cli]/[execa]/index.js:114:26

  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5

  - init-starter.js:135 install
    [npm]/[gatsby-cli]/lib/init-starter.js:135:7

  - init-starter.js:202 clone
    [npm]/[gatsby-cli]/lib/init-starter.js:202:3

  - init-starter.js:343 initStarter
    [npm]/[gatsby-cli]/lib/init-starter.js:343:5

  - create-cli.js:449
    [npm]/[gatsby-cli]/lib/create-cli.js:449:9

**Comment by kosvrouvas** [comment]
Wow, I don't know why I missed this one.

Truth is I cannot replicate your issue. Any chances you still got that debug log? On what system are you rinning this?
